/*
  Recuerda que deshabilitar la opción "Enable foreign key checks" para evitar problemas a la hora de importar el script.
*/
DROP TABLE IF EXISTS PERSONA;
/*DROP TABLE IF EXISTS USUARIO;*/
DROP TABLE IF EXISTS SERVICIO;
DROP TABLE IF EXISTS FORO;
DROP TABLE IF EXISTS COMENTARIOS_FORO;
DROP TABLE IF EXISTS MONEDERO;
DROP TABLE IF EXISTS RESENA;
/*DROP TABLE IF EXISTS MENSAJES;*/
DROP TABLE IF EXISTS DISPONIBILIDAD_USUARIO;
DROP TABLE IF EXISTS SERVICIOS_CONTRATADOS;
DROP TABLE IF EXISTS SERVICIOS_REALIZADOS;
DROP TABLE IF EXISTS SERVICIOS_FAVORITOS;
DROP TABLE IF EXISTS SERVICIOS_SOLICITADOS;
DROP TABLE IF EXISTS CATEGORIA_SERVICIOS;



/*ENTIDADES*/

/*CREATE TABLE MENSAJES(
    ID                 INT              NOT NULL,
    USUARIO_REMITENTE  INT              NOT NULL,
    USUARIO_DESTINATARIO  INT           NOT NULL,
    CONTENIDO          VARCHAR(300)     NOT NULL,
    FECHA_ENVIO        DATE             NOT NULL,
    FECHA_RECEPCION    DATE             NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;*/


CREATE TABLE PERSONA(
    NIF                 VARCHAR(9)      NOT NULL,
    NOMBRE              VARCHAR(50)  	NOT NULL,
    APELLIDO1           VARCHAR(50)  	NOT NULL,
    APELLIDO2           VARCHAR(50)  	NOT NULL,
    SEXO                VARCHAR(1)  	NULL,
    FECHA_NACIMIENTO    DATE            NULL,			   	
    PAIS                VARCHAR(50)  	NOT NULL,
    CIUDAD              VARCHAR(50)     NOT NULL,
    CALLE               VARCHAR(75)  	NOT NULL,
    NUMERO_CALLE        VARCHAR(10)     NULL,
    PORTAL 				VARCHAR(6)   	NULL,
    PISO 				VARCHAR(12)  	NULL,
    PUERTA 				VARCHAR(10)     NULL,
    CODIGO_POSTAL 		VARCHAR(5)   	NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE SERVICIO(
    ID                  INT             NOT NULL,
    TITULO              VARCHAR(250)    NOT NULL,
    COSTE               INT			    NOT NULL,
    CATEGORIA_SERVICIOS INT             NOT NULL,
    DESCRIPCION         VARCHAR(250)    NOT NULL
    /*IMAGEN              varbinary*/
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Tema libre (Se puede modificar)*/
CREATE TABLE FORO(
    ID                  INT             NOT NULL,
    TEMA_FOROS          VARCHAR(100)    NOT NULL,
    ASUNTO              VARCHAR(100)    NOT NULL
    /*USUARIO_CREADOR     INT             NOT NULL*/
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE COMENTARIOS_FORO(
    ID                  INT             NOT NULL,
    ID_MENSAJE_PADRE    INT             NULL,
    FORO                INT             NOT NULL,
    CONTENIDO           VARCHAR(300)    NOT NULL,
    USUARIO_CREADOR     INT             NOT NULL,
    FECHA_CREACION      DATE            NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE MONEDERO(
    ID                 INT              NOT NULL,
    USUARIO            INT              NOT NULL,
    SALDO              INT              NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE RESENA(
    ID                 INT              NOT NULL,
    USUARIO_CREADOR    INT              NOT NULL,
    USUARIO_VALORADO   INT              NOT NULL,
    PUNTUACION         INT              NOT NULL,
    COMENTARIO         VARCHAR(300)     NOT NULL,
    FECHA_VALORACION   DATE             NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


/*POR DEFINIR*/
CREATE TABLE DISPONIBILIDAD_USUARIO(
    ID                 INT              NOT NULL,
    FECHA              DATE             NOT NULL,
    /*FECHA_FIN       DATE                NOT NULL,*/
    USUARIO            INT              NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*RELACIONES*/

CREATE TABLE SERVICIOS_CONTRATADOS(
    ID                   INT            NOT NULL,
    USUARIO_CONTRATADOR  INT            NOT NULL,
    SERVICIO             INT            NOT NULL,
    FECHA_CONTRATACION   DATE           NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*DEFINIR SI SE QUIEREN UNIFICAR AMBAS TABLAS*/
CREATE TABLE SERVICIOS_REALIZADOS(
    ID                  INT             NOT NULL,
    USUARIO             INT             NOT NULL, /*El que ofrece el servicio*/
    SERVICIO            INT             NOT NULL,
    FECHA_REALIZACION   DATE            NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SERVICIOS_FAVORITOS(
ID                          INT          NOT NULL,
USUARIO                     INT          NOT NULL,
SERVICIO                    INT          NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SERVICIOS_SOLICITADOS(
ID                          INT          NOT NULL,
USUARIO                     INT          NOT NULL,
SERVICIO                    INT          NOT NULL,
FECHA_SOLICITUD             DATE         NOT NULL
/*SE PUEDE AGREGAR EL USUARIO SOLICITADO*/
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CATEGORIA_SERVICIOS(
ID                          INT          NOT NULL,
NOMBRE                      VARCHAR(50)  NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


/*CREATE TABLE CATEGORIA_FOROS(
   ID                          INT          NOT NULL,
   NOMBRE                      VARCHAR(50 CHAR)  	NOT NULL,
);*/

/*CREATE TABLE IF NOT EXISTS `Mensajes` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `usuario` int(11) NOT NULL,
    `mensaje` varchar(140) NOT NULL,
    `idMensajePadre` int(11) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `usuario` (`usuario`),
    KEY `idMensajePadre` (`idMensajePadre`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4;
*/

/*CREATE TABLE HILO(
    ID                      INT          NOT NULL,
    USUARIO_CREADOR         VARCHAR(100) 	NOT NULL,
    FECHA_CREACION          DATE                NOT NULL
);*/

/*CONSTRAINTS*/

ALTER TABLE PERSONA                 ADD CONSTRAINT PERSONA_PK                                   PRIMARY KEY (NIF);
/*ALTER TABLE USUARIOS                 ADD CONSTRAINT USUARIOS_PK                                   PRIMARY KEY (ID, NIF);*/
ALTER TABLE SERVICIO                ADD CONSTRAINT SERVICIO_PF                                  PRIMARY KEY (ID);
ALTER TABLE FORO                    ADD CONSTRAINT FORO_PK                                      PRIMARY KEY (ID);
ALTER TABLE COMENTARIOS_FORO        ADD CONSTRAINT COMENTARIOS_FORO_PK                          PRIMARY KEY (ID);
ALTER TABLE MONEDERO                ADD CONSTRAINT MONEDERO_PK                                  PRIMARY KEY (ID);
ALTER TABLE RESENA                  ADD CONSTRAINT RESENA_PK                                    PRIMARY KEY (ID);
/*ALTER TABLE MENSAJES                ADD CONSTRAINT MENSAJES_PK                                  PRIMARY KEY (ID);*/
ALTER TABLE DISPONIBILIDAD_USUARIO  ADD CONSTRAINT DISPONIBILIDAD_USUARIO_PK                    PRIMARY KEY (ID);
ALTER TABLE SERVICIOS_CONTRATADOS   ADD CONSTRAINT SERVICIOS_CONTRATADOS_PK                     PRIMARY KEY (ID);
ALTER TABLE SERVICIOS_REALIZADOS    ADD CONSTRAINT SERVICIOS_REALIZADOS_PK                      PRIMARY KEY (ID);
ALTER TABLE SERVICIOS_FAVORITOS     ADD CONSTRAINT SERVICIOS_FAVORITOS_PK                       PRIMARY KEY (ID);
ALTER TABLE SERVICIOS_SOLICITADOS   ADD CONSTRAINT SERVICIOS_SOLICITADOS_PK                     PRIMARY KEY (ID);
ALTER TABLE CATEGORIA_SERVICIOS     ADD CONSTRAINT CATEGORIA_SERVICIOS_PK                       PRIMARY KEY (ID);


/*ALTER TABLE USUARIOS                 ADD CONSTRAINT USUARIOS_UQ                                   UNIQUE (EMAIL);*/
ALTER TABLE CATEGORIA_SERVICIOS     ADD CONSTRAINT NOMBRE_UQ                                    UNIQUE (NOMBRE);

/*ALTER TABLE USUARIOS                 ADD CONSTRAINT USUARIOS_NIF_FK                               FOREIGN KEY (NIF)                       REFERENCES PERSONA(NIF);*/
/*ALTER TABLE `Mensajes`              ADD CONSTRAINT `Mensajes_mensaje`                           FOREIGN KEY (`idMensajePadre`)      REFERENCES `Mensajes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;*/
ALTER TABLE SERVICIO                ADD CONSTRAINT SERVICIO_CATEGORIA_SERVICIOS_FK              FOREIGN KEY(CATEGORIA_SERVICIOS)       REFERENCES CATEGORIA_SERVICIOS(ID);
/*ALTER TABLE FORO                    ADD CONSTRAINT FORO_TEMA_FOROS_FK                           FOREIGN KEY(TEMA_FOROS)                 REFERENCES CATEGORIA_SERVICIOS(ID);*/
/*ALTER TABLE FORO                    ADD CONSTRAINT FORO_USUARIO_CREADOR_FOROS_FK                FOREIGN KEY (USUARIO_CREADOR)           REFERENCES USUARIOS(ID);*/
ALTER TABLE COMENTARIOS_FORO        ADD CONSTRAINT COMENTARIOS_FORO_ID_MENSAJE_PADRE_FK         FOREIGN KEY(ID_MENSAJE_PADRE)           REFERENCES COMENTARIOS_FORO(ID);
ALTER TABLE COMENTARIOS_FORO        ADD CONSTRAINT COMENTARIOS_FORO_FORO_FK                     FOREIGN KEY(FORO)                       REFERENCES FORO(ID);
ALTER TABLE COMENTARIOS_FORO        ADD CONSTRAINT COMENTARIOS_FORO_USUARIO_CREADOR_FK          FOREIGN KEY (USUARIO_CREADOR)           REFERENCES USUARIOS(ID);
ALTER TABLE MONEDERO                ADD CONSTRAINT MONEDERO_USUARIO_FK                          FOREIGN KEY (USUARIO)                   REFERENCES USUARIOS(ID);
ALTER TABLE RESENA                  ADD CONSTRAINT RESENA_USUARIO_CREADOR_FK                    FOREIGN KEY (USUARIO_CREADOR)           REFERENCES USUARIOS(ID);
ALTER TABLE RESENA                  ADD CONSTRAINT RESENA_USUARIO_VALORADO_FK                   FOREIGN KEY (USUARIO_VALORADO)          REFERENCES USUARIOS(ID);

ALTER TABLE DISPONIBILIDAD_USUARIO  ADD CONSTRAINT DISPONIBILIDAD_USUARIO_USUARIO_FK            FOREIGN KEY (USUARIO)                   REFERENCES USUARIOS(ID);
ALTER TABLE SERVICIOS_CONTRATADOS   ADD CONSTRAINT SERVICIOS_CONTRATADOS_USUARIO_CONTRATADOR_FK FOREIGN KEY(USUARIO_CONTRATADOR)        REFERENCES USUARIOS(ID);
ALTER TABLE SERVICIOS_CONTRATADOS   ADD CONSTRAINT SERVICIOS_CONTRATADOS_SERVICIO_FK            FOREIGN KEY(SERVICIO)                   REFERENCES SERVICIO(ID);
ALTER TABLE SERVICIOS_REALIZADOS    ADD CONSTRAINT SERVICIOS_REALIZADOS_USUARIO_FK              FOREIGN KEY(USUARIO)                    REFERENCES USUARIOS(ID);
ALTER TABLE SERVICIOS_REALIZADOS    ADD CONSTRAINT SERVICIOS_REALIZADOS_SERVICIO_FK             FOREIGN KEY(SERVICIO)                   REFERENCES SERVICIO(ID);
ALTER TABLE SERVICIOS_FAVORITOS     ADD CONSTRAINT SERVICIOS_FAVORITOS_USUARIO_FK               FOREIGN KEY(USUARIO)                    REFERENCES USUARIOS(ID);
ALTER TABLE SERVICIOS_FAVORITOS     ADD CONSTRAINT SERVICIOS_FAVORITOS_SERVICIO_FK              FOREIGN KEY(SERVICIO)                   REFERENCES SERVICIO(ID);
ALTER TABLE SERVICIOS_SOLICITADOS   ADD CONSTRAINT SERVICIOS_SOLICITADOS_USUARIO_FK             FOREIGN KEY(USUARIO)                    REFERENCES USUARIOS(ID);
ALTER TABLE SERVICIOS_SOLICITADOS   ADD CONSTRAINT SERVICIOS_SOLICITADOS_SERVICIO_FK            FOREIGN KEY(SERVICIO)                   REFERENCES SERVICIO(ID);



/*ALTER TABLE USUARIO                 MODIFY ID INT NOT NULL AUTO_INCREMENT;*/
ALTER TABLE SERVICIO                MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE FORO                    MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE COMENTARIOS_FORO        MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE MONEDERO                MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE RESENA                  MODIFY ID INT NOT NULL AUTO_INCREMENT;
/*ALTER TABLE MENSAJES                MODIFY ID INT NOT NULL AUTO_INCREMENT;*/
ALTER TABLE DISPONIBILIDAD_USUARIO  MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE SERVICIOS_CONTRATADOS   MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE SERVICIOS_REALIZADOS    MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE SERVICIOS_FAVORITOS     MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE SERVICIOS_SOLICITADOS   MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE CATEGORIA_SERVICIOS     MODIFY ID INT NOT NULL AUTO_INCREMENT;