--ENTIDADES
CREATE TABLE PERSONA(
    NIF                 VARCHAR2(9)         NOT NULL,
    NOMBRE              VARCHAR2(50 CHAR)  	NOT NULL,
    APELLIDO1           VARCHAR2(50 CHAR)  	NOT NULL,
    APELLIDO2           VARCHAR2(50 CHAR)  	NOT NULL,
    SEXO                VARCHAR2(1 CHAR)  	NULL,
    FECHA_NACIMIENTO    DATE                NULL,			   	
    PAIS                VARCHAR2(50 CHAR)  	NOT NULL,
    CIUDAD              VARCHAR2(50 CHAR)   NOT NULL,
    CALLE               VARCHAR2(75 CHAR)  	NOT NULL,
    NUMERO_CALLE        VARCHAR2(10 CHAR)   NULL,
    PORTAL 				VARCHAR2(6 CHAR)   	NULL,
    PISO 				VARCHAR2(12 CHAR)  	NULL,
    PUERTA 				VARCHAR2(10 CHAR)   NULL,
    CODIGO_POSTAL 		VARCHAR2(5 CHAR)   	NOT NULL
);
CREATE TABLE USUARIO(
    ID                  NUMBER(10)          NOT NULL,
    NIF                 VARCHAR2(9)         NOT NULL,
    EMAIL               VARCHAR2(100 CHAR) 	NOT NULL,
    CONTRASENA      	VARCHAR2(20 CHAR) 	NOT NULL,
    TELEFONO            NUMBER(9) 		   	NOT NULL,
    IMAGEN              
    DESCRIPCION         VARCHAR2(250 CHAR)  NULL,
    DISPONIBILIDAD      NUMBER(10)          NOT NULL, --POR DEFINIR
    SERVICIO_OFERTADO   NUMBER(10)          NULL,
    MONEDERO            NUMBER(10)          NOT NULL,
    FECHA_CREACION      DATE                NOT NULL
);  
CREATE TABLE SERVICIO(
    ID                  NUMBER(10)          NOT NULL,
    TITULO              VARCHAR2(250 CHAR)  NOT NULL,
    COSTE               NUMBER(10)			NOT NULL,
    CATEGORIA_SERVICIOS NUMBER(10)          NOT NULL,
    DESCRIPCION         VARCHAR2(250 CHAR)  NOT NULL
    IMAGEN
);
--Tema libre (Se puede modificar)
CREATE TABLE FORO(
    ID                      NUMBER(10)          NOT NULL,
    TEMA_FOROS              NUMBER(10)          NOT NULL,--CLAVE DE TABLA CATEGORIA_SERVICIOS
    ASUNTO                  VARCHAR2(100 CHAR) 	NOT NULL  
);
--CREATE TABLE HILO(
--    ID                      NUMBER(10)          NOT NULL,
--    USUARIO_CREADOR         VARCHAR2(100 CHAR) 	NOT NULL,
--    FECHA_CREACION          DATE                NOT NULL
--);
CREATE TABLE COMENTARIOS_FORO(
    ID                          NUMBER(10)          NOT NULL,
    ID_MENSAJE_PADRE            NUMBER(10)          NULL,
    FORO                        NUMBER(10)          NOT NULL,
    CONTENIDO                   VARCHAR2(300 CHAR) 	NOT NULL,
    USUARIO_CREADOR             NUMBER(10)          NOT NULL,
    FECHA_CREACION              DATE                NOT NULL
);
CREATE TABLE MONEDERO(
    ID                      NUMBER(10)          NOT NULL,
    USUARIO                 NUMBER(10)          NOT NULL,
    SALDO                   NUMBER(100)         NOT NULL
);
CREATE TABLE RESENA(
    ID                      NUMBER(10)          NOT NULL,
    USUARIO_CREADOR         NUMBER(10)          NOT NULL,
    USUARIO_VALORADO        NUMBER(10)          NOT NULL,
    PUNTUACION              NUMBER(1)           NOT NULL,
    COMENTARIO              VARCHAR2(300 CHAR)  NOT NULL,
    FECHA_VALORACION        DATE                NOT NULL
);
CREATE TABLE MENSAJES(
    ID                      NUMBER(10)          NOT NULL,
    USUARIO_REMITENTE       NUMBER(10)          NOT NULL,
    USUARIO_DESTINATARIO    NUMBER(10)          NOT NULL,
    CONTENIDO               VARCHAR2(300 CHAR) 	NOT NULL,
    FECHA_ENVIO             DATE                NOT NULL,
    FECHA_RECEPCION         DATE                NULL
);
/*CREATE TABLE IF NOT EXISTS `Mensajes` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `usuario` int(11) NOT NULL,
    `mensaje` varchar(140) NOT NULL,
    `idMensajePadre` int(11) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `usuario` (`usuario`),
    KEY `idMensajePadre` (`idMensajePadre`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4  COLLATE=utf8mb4_spanish_ci;
*/

--POR DEFINIR
CREATE TABLE DISPONIBILIDAD_USUARIO(
    ID              NUMBER(10)          NOT NULL,
    FECHA           DATE                NOT NULL,
 -- FECHA_FIN       DATE                NOT NULL,
    USUARIO         NUMBER(10)          NOT NULL
);

--RELACIONES

CREATE TABLE SERVICIOS_CONTRATADOS(
    ID                          NUMBER(10)          NOT NULL,
    USUARIO_CONTRATADOR         NUMBER(10)          NOT NULL,
    SERVICIO                    NUMBER(10)          NOT NULL,
    FECHA_CONTRATACION          DATE                NOT NULL
);
--DEFINIR SI SE QUIEREN UNIFICAR AMBAS TABLAS
CREATE TABLE SERVICIOS_REALIZADOS(
    ID                          NUMBER(10)          NOT NULL,
    USUARIO                     NUMBER(10)          NOT NULL, --El que ofrece el servicio
    SERVICIO                    NUMBER(10)          NOT NULL,
    FECHA_REALIZACION           DATE                NOT NULL
);

CREATE TABLE SERVICIOS_FAVORITOS(
    ID                          NUMBER(10)          NOT NULL,
    USUARIO                     NUMBER(10)          NOT NULL,
    SERVICIO                    NUMBER(10)          NOT NULL
);

CREATE TABLE SERVICIOS_SOLICITADOS(
    ID                          NUMBER(10)          NOT NULL,
    USUARIO                     NUMBER(10)          NOT NULL,
    SERVICIO                    NUMBER(10)          NOT NULL,
    FECHA_SOLICITUD             DATE                NOT NULL
    --SE PUEDE AGREGAR EL USUARIO SOLICITADO
);

CREATE TABLE CATEGORIA_SERVICIOS(
    ID                          NUMBER(10)          NOT NULL,
    NOMBRE                      VARCHAR2(50 CHAR)  	NOT NULL
);


--CREATE TABLE CATEGORIA_FOROS(
--    ID                          NUMBER(10)          NOT NULL,
--    NOMBRE                      VARCHAR2(50 CHAR)  	NOT NULL,
--);

--CONSTRAINTS
ALTER TABLE PERSONA 
    ADD CONSTRAINT PERSONA_PK PRIMARY KEY (NIF);

ALTER TABLE USUARIO 
    ADD CONSTRAINT USUARIO_PK PRIMARY KEY (ID, NIF),
    ADD CONSTRAINT USUARIO_UQ UNIQUE (EMAIL),
    ADD CONSTRAINT USUARIO_FK FOREIGN KEY (NIF) REFERENCES (PERSONA);

ALTER TABLE SERVICIO 
    ADD CONSTRAINT SERVICIO_PF PRIMARY KEY (ID),
    ADD CONSTRAINT CATEGORIA_SERVICIOS_FK FOREIGN KEY(CATEGORIA_SERVICIOS) REFERENCES(CATEGORIA_SERVICIOS);

ALTER TABLE FORO 
    ADD CONSTRAINT FORO_PK   PRIMARY KEY (ID),
    ADD CONSTRAINT TEMA_FOROS_FK FOREIGN KEY(TEMA_FOROS) REFERENCES(CATEGORIA_SERVICIOS);

ALTER TABLE COMENTARIOS_FORO 
    ADD CONSTRAINT COMENTARIOS_FORO_PK   PRIMARY KEY (ID),
    ADD CONSTRAINT ID_MENSAJE_PADRE_FK FOREIGN KEY(ID_MENSAJE_PADRE) REFERENCES(CATEGORIA_SERVICIOS),
    ADD CONSTRAINT FORO_FK FOREIGN KEY(FORO),
    ADD CONSTRAINT USUARIO_CREADOR_FK FOREIGN KEY (USUARIO);
    
ALTER TABLE MONEDERO 
    ADD CONSTRAINT MONEDERO_PK   PRIMARY KEY (ID);
    ADD CONSTRAINT USUARIO_FK FOREIGN KEY (USUARIO);
        
ALTER TABLE RESENA 
    ADD CONSTRAINT RESENA_PK   PRIMARY KEY (ID);

ALTER TABLE MENSAJES 
    ADD CONSTRAINT MENSAJES_PK   PRIMARY KEY (ID);

ALTER TABLE DISPONIBILIDAD_USUARIO 
    ADD CONSTRAINT DISPONIBILIDAD_USUARIO_PK   PRIMARY KEY (ID);
    
ALTER TABLE SERVICIOS_CONTRATADOS 
    ADD CONSTRAINT SERVICIOS_CONTRATADOS_PK   PRIMARY KEY (ID),
    ADD CONSTRAINT USUARIO_CONTRATADOR_FK FOREIGN KEY(USUARIO_CONTRATADOR) REFERENCES (USUARIO),
    ADD CONSTRAINT SERVICIO_FK FOREIGN KEY(SERVICIO) REFERENCES (SERVICIO);

ALTER TABLE SERVICIOS_REALIZADOS 
    ADD CONSTRAINT SERVICIOS_REALIZADOS_PK   PRIMARY KEY (ID),
    ADD CONSTRAINT USUARIO_FK FOREIGN KEY(USUARIO) REFERENCES (USUARIO),
    ADD CONSTRAINT SERVICIO_FK FOREIGN KEY(SERVICIO) REFERENCES (SERVICIO);

ALTER TABLE SERVICIOS_FAVORITOS 
    ADD CONSTRAINT SERVICIOS_FAVORITOS_PK   PRIMARY KEY (ID),
    ADD CONSTRAINT USUARIO_FK FOREIGN KEY(USUARIO) REFERENCES (USUARIO),
    ADD CONSTRAINT SERVICIO_FK FOREIGN KEY(SERVICIO) REFERENCES (SERVICIO);

ALTER TABLE SERVICIOS_SOLICITADOS 
    ADD CONSTRAINT SERVICIOS_SOLICITADOS_PK   PRIMARY KEY (ID),
    ADD CONSTRAINT USUARIO_FK FOREIGN KEY(USUARIO) REFERENCES (USUARIO),
    ADD CONSTRAINT SERVICIO_FK FOREIGN KEY(SERVICIO) REFERENCES (SERVICIO);

ALTER TABLE CATEGORIA_SERVICIOS 
    ADD CONSTRAINT CATEGORIA_SERVICIOS_PK   PRIMARY KEY (ID),
    ADD CONSTRAINT NOMBRE_UQ UNIQUE (NOMBRE);

